// Generated By NPM Crud Author<hello@imritesh.com>

export interface ICreateUsers {
     name: string; 
 email: string; 
 mobile: string; 
 password: string; 
}
export interface IEditUsers {
  id: number;
}

export interface IUpdateUsers {
    id: number;
    name : string; 
email : string; 
mobile : string; 
password : string; 
}
export interface IDeleteUsers {
  id: number;
}

    